Reports flow
ASKU-PI/asku-client pull request #71
Opened 2021-11-09 01:35 UTC by Tumilok

# Why
This changes allow moderators to view and respond for reports.

# What
* Add reports list page
* Add modals to check the details of the reports
* Enable closing/reopening reports
* Secure the reports url

2021-11-12 23:27 UTC, Andrzejska requested changes
Jest Good, tylko obsługa errorów przez catch i addAlert

2021-11-12 23:27 UTC, Andrzejska commented on src/common/interfaces/reports/Report.tsx
> +interface Profile {
taki model jest już w resources

2021-11-12 23:27 UTC, Andrzejska commented on src/common/interfaces/resources/UserInfo.tsx
> +export const isModerator = (userInfo: UserInfo): boolean => {
includes() - funkcja js

2021-11-12 23:27 UTC, Andrzejska commented on src/modules/reports/reportCards/Cardholder.tsx
> +          dispatch(addAlert(`Couldn't fetch ${reports} reports`, 'error'));
nie jest to do wrzucenia w catch()?

2021-11-12 23:27 UTC, Andrzejska commented on src/modules/reports/reportCards/Cardholder.tsx
> +    let isMounted = true;
po co jest ten isMounted? jeżeli każdy raz ustawiamy go na true przy zmianie [needsUpdate, reportsPage]?

2021-11-12 23:27 UTC, Andrzejska commented on src/modules/reports/reportCards/ReportDetailsDialog.tsx
> +      if (res !== null) {
catch()?

2021-11-12 23:27 UTC, Andrzejska commented on src/services/ReportService.tsx
> +    return null;
addAlert?

2021-11-12 23:27 UTC, Andrzejska commented on src/services/ReportService.tsx
> +    console.log('Fetching reports failed: ' + err);
addAlert?

2021-11-12 23:27 UTC, Andrzejska commented on src/services/SpaceService.tsx
> +    console.log('Deleting  space failed: ' + err);
addAlert?

2021-11-13 11:13 UTC, Tumilok commented on src/common/interfaces/reports/Report.tsx
> +interface Profile {
Właśnie zapomniałem o tym

2021-11-13 11:15 UTC, Tumilok commented on src/common/interfaces/resources/UserInfo.tsx
> +export const isModerator = (userInfo: UserInfo): boolean => {
Właśnie próbowałem jej użyć, ale coś nie działało. Spróbuję jeszcze raz

2021-11-13 14:26 UTC, Tumilok commented on src/common/interfaces/resources/UserInfo.tsx
> +export const isModerator = (userInfo: UserInfo): boolean => {
działa

2021-11-13 16:05 UTC, Andrzejska approved these changes
Jazda Jazda

2021-11-13 16:05 UTC, merged