chat, fb login + register, profile update
ASKU-PI/asku-client pull request #74
Opened 2021-11-11 23:15 UTC by sswrk

2021-11-12 12:10 UTC, Tumilok approved these changes
Approve with minor comments 🚀

2021-11-12 12:10 UTC, Tumilok commented on src/common/interfaces/resources/MessageInfo.tsx
> +// TODO: fill while connecting chat with back
Pytanie jak wcześniej, czy to jeszcze do zrobienia?

2021-11-12 12:10 UTC, Tumilok commented on src/common/interfaces/resources/ProfileInfo.tsx
> +  file?: File;
Czym jest file?

2021-11-12 12:10 UTC, Tumilok commented on src/common/interfaces/resources/ProfileInfo.tsx
> +  email?: string;
Czy dobrze rozumiem, `email` jest nullable z za rejestracji przez facebook?

2021-11-12 12:10 UTC, Tumilok commented on src/modules/addSpace/PhotosDragDrop.tsx
> +import React from 'react';
Czy ta linijka jest potrzebna?

2021-11-12 12:10 UTC, Tumilok commented on src/modules/ownedSpacesReservations/OwnedSpacesReservations.tsx
> +import Profile from '../profile/Profile';
Ten import nie jest używany

2021-11-12 12:12 UTC, Andrzejska commented on package.json
> +    "start": "set HTTPS=true && react-scripts start",
facebook nie chce obsługiwać pytania od niezabezpieczonych stron typu http

2021-11-12 12:17 UTC, Andrzejska requested changes
Changes zgodnie z uwagami @Tumilok

2021-11-12 12:17 UTC, Andrzejska commented on src/common/interfaces/resources/ChatInfo.tsx
> +// TODO: fill while connecting chat with back
Już nie, trzeba to usunąć

2021-11-12 12:17 UTC, Andrzejska commented on src/common/interfaces/resources/MessageInfo.tsx
> +// TODO: fill while connecting chat with back
Same, nie

2021-11-12 12:17 UTC, Andrzejska commented on src/common/interfaces/resources/ProfileInfo.tsx
> +  email?: string;
Tak jest

2021-11-12 12:17 UTC, Andrzejska commented on src/modules/addSpace/PhotosDragDrop.tsx
> +import React from 'react';
Każdy raz mi interpreter podpowiada, że jest wykorzystanie jakiegoś tam componentu per importu React. Więc tylko przez to dodaję.

2021-11-12 12:17 UTC, Andrzejska commented on src/common/interfaces/resources/ProfileInfo.tsx
> +  file?: File;
Dobre pytanie, jak jest już avatar to file to nic

2021-11-12 12:17 UTC, Andrzejska commented on src/modules/ownedSpacesReservations/OwnedSpacesReservations.tsx
> +import Profile from '../profile/Profile';
Do naprawy

2021-11-12 12:20 UTC, Tumilok commented on package.json
> +    "start": "set HTTPS=true && react-scripts start",
Czy to wpływa jakoś na reszte aplikacji?

2021-11-12 12:20 UTC, Tumilok commented on src/common/interfaces/resources/ProfileInfo.tsx
> +  file?: File;
To usuwamy :)

2021-11-12 12:23 UTC, Andrzejska commented on package.json
> +    "start": "set HTTPS=true && react-scripts start",
Zgodnie z google: Https (or Hyper Text Transfer Protocol Secure) is the answer to the data protection issue. Used on sites that feature eCommerce, banking, and even just a login page, https protects data by encrypting it before sending it either way by using an SSL (Secure Sockets Layer) Certificate.

2021-11-12 13:00 UTC, Andrzejska approved these changes
SGTM

2021-11-12 16:15 UTC, wnekus approved these changes
:rocket: :rocket: :rocket:

2021-11-13 00:13 UTC, Andrzejska approved these changes
Jazda Jazda

2021-11-13 00:13 UTC, merged